dynatrace-oss/dt-cli

dtcli/building.py
Comment moved to main zip and looks like this:
```
Generator: dt-cli 0.0.7-alpha
Creation-time: 2021-06-25T09:00:28Z
```
=> Embed-metadata-in-zip-archive

dtcli/scripts/dt.py
Trying to overcome unavailable reviewers problem ;)
=> Command-gendevcert-does-not-generate-developer-key

.bumpversion.cfg, dtcli/__init__.py, pyproject.toml
Trying to overcome unavailable reviewers problem ;)
=> Bump version: 0.1.2-alpha → 0.1.3-alpha

dtcli/scripts/dt.py, dtcli/utils.py
* better general help text
* typo in prepare-python command (hidden)
* provide information about extension naming format
=> Improvements based on feedback

dtcli/scripts/dt.py
=> additional hint concerning extension directory

.github/workflows/built-test-release.yml, dtcli/building.py, dtcli/constants.py, dtcli/scripts/dt.py, dtcli/signing.py, tests/test_signing.py
* Increase default key size to 4096 bytes
* Shorten default dev cert validity, allow to set value via param
=> security-improvements-1

dtcli/signing.py
Copy of #47 done from the correct repository
=> add cert extensions

dtcli/building.py, dtcli/scripts/dt.py, dtcli/signing.py, tests/test_signing.py
Reverts dynatrace-oss/dt-cli#52
Those changes need to be reverted for now as the ECC certificate cannot be verified in Dynatrace or on EEC side
=> Revert "Elliptic Curve Cryptography (ECC) new default instead of RSA (issue #48)"

.gitignore, dtcli/building.py
=> Add better yaml parser error

.bumpversion.cfg, dtcli/scripts/dt.py, dtcli/version.py, pyproject.toml
Discovered when implementing APM-364102, esentially an uncaught mypy
problem
=> Fix failing `dt ext assemble` command

dtcli/constants.py, dtcli/scripts/dt.py
=> Extract default build output

.bumpversion.cfg, dtcli/constants.py, dtcli/scripts/dt.py, dtcli/signing.py, dtcli/utils.py, dtcli/version.py, pyproject.toml
Use lesser permissions by default and check for those permissions when
operating
=> [APM-364102] Improve key security

.bumpversion.cfg, dtcli/scripts/dt.py, dtcli/version.py, pyproject.toml
Certainly the write was a bad idea, since the entire nix store is read
only ;d
=> Fix required path properties for validate_schema

.github/workflows/built-test-release.yml, Makefile, dtcli/api.py
=> Enable basic mypy checking

.flake8, dtcli/__main__.py, dtcli/constants.py, dtcli/scripts/dt.py, poetry.lock, pyproject.toml
I think there is an immense value added by using Typer and the
integration is quite well though out. It required only minimal tweaking
and configuration, the glue code is reasonable and the lines are net
reduced after migrating just one command.
Resolves #16
=> Add typer support and migrate sign

.bumpversion.cfg, dtcli/signing.py, dtcli/version.py, pyproject.toml
Turns out that ordering matters - this should stop a class of bugs
=> Fix fused certkey generation

.github/workflows/built-test-release.yml
Given enough eyes all bugs are shallow
Right?
=> Add missing tag invocation

dtcli/api.py, dtcli/click_helpers.py, dtcli/scripts/dt.py
=> Change error reporting from stack trace to short message

dtcli/building.py, dtcli/scripts/dt.py
=> Compress with ZIP_DEFLATED

dtcli/building.py, dtcli/scripts/dt.py, dtcli/signing.py
Provide a nicer error message for #99
=> Nicer error message on malformed certkey

.bumpversion.cfg, Makefile, dtcli/api.py, dtcli/delete_extension.py, dtcli/scripts/dt.py, dtcli/version.py, pyproject.toml
=> Change pageSize value equal to totalCount 

.bumpversion.cfg, .github/workflows/built-test-release.yml, Dockerfile, dtcli/version.py, poetry.lock, pyproject.toml
=> Static binary

README.md, dtcli/scripts/dt.py
=> Fix typo in certificate generation instructions

README.md
=> Fixed the link in build status badge in README
